# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apply_comp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(383, 273)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 220, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 341, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.CH1 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.CH1.setObjectName("CH1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CH1)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.CH2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.CH2.setObjectName("CH2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.CH2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox.setDecimals(8)
        self.doubleSpinBox.setProperty("value", 1.235)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.comp_name1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.comp_name1.setObjectName("comp_name1")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comp_name1)
        self.comp_name2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.comp_name2.setObjectName("comp_name2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comp_name2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.compCH = QtWidgets.QComboBox(self.formLayoutWidget)
        self.compCH.setObjectName("compCH")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.compCH)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Apply compensation channel"))
        self.label.setText(_translate("Dialog", "Channel #1"))
        self.label_2.setText(_translate("Dialog", "Channel #2"))
        self.label_3.setText(_translate("Dialog", "K"))
        self.comp_name1.setText(_translate("Dialog", "diff1"))
        self.comp_name2.setText(_translate("Dialog", "diff2"))
        self.label_4.setText(_translate("Dialog", "Ch1 - Comp name"))
        self.label_5.setText(_translate("Dialog", "Ch2 - Comp name"))
        self.label_6.setText(_translate("Dialog", "Compensation channel"))
