# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(483, 384)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 330, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 441, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBoxNumIMF = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBoxNumIMF.setProperty("value", 15)
        self.spinBoxNumIMF.setObjectName("spinBoxNumIMF")
        self.gridLayout.addWidget(self.spinBoxNumIMF, 0, 3, 1, 1)
        self.radioButtonAll = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonAll.setObjectName("radioButtonAll")
        self.gridLayout.addWidget(self.radioButtonAll, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.comboBoxCH = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBoxCH.setObjectName("comboBoxCH")
        self.gridLayout.addWidget(self.comboBoxCH, 2, 1, 1, 2)
        self.radioButtonNew = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonNew.setObjectName("radioButtonNew")
        self.gridLayout.addWidget(self.radioButtonNew, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 5, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButtonDecompose = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonDecompose.setObjectName("pushButtonDecompose")
        self.gridLayout.addWidget(self.pushButtonDecompose, 3, 2, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.spinBoxMaxIt = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBoxMaxIt.setProperty("value", 7)
        self.spinBoxMaxIt.setObjectName("spinBoxMaxIt")
        self.gridLayout.addWidget(self.spinBoxMaxIt, 1, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setProperty("value", 0.001)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.spinBoxNumExtr = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBoxNumExtr.setProperty("value", 3)
        self.spinBoxNumExtr.setObjectName("spinBoxNumExtr")
        self.gridLayout.addWidget(self.spinBoxNumExtr, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.comboBoxIMF = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBoxIMF.setObjectName("comboBoxIMF")
        self.gridLayout.addWidget(self.comboBoxIMF, 4, 1, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "EMD"))
        self.radioButtonAll.setText(_translate("Dialog", "Save all IMFs"))
        self.label_5.setText(_translate("Dialog", "Channel"))
        self.radioButtonNew.setText(_translate("Dialog", "Save as new trace"))
        self.label.setText(_translate("Dialog", "Sift Relative Tolerance"))
        self.lineEdit.setText(_translate("Dialog", "diff1_imf8"))
        self.label_2.setText(_translate("Dialog", "Sift Max Iteration"))
        self.pushButtonDecompose.setText(_translate("Dialog", "Decompose"))
        self.label_4.setText(_translate("Dialog", "Max Num Extrema"))
        self.label_3.setText(_translate("Dialog", "Max Num IMF"))
        self.label_6.setText(_translate("Dialog", "IMF"))
