# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 306)
        self.pushButtonClose = QtWidgets.QPushButton(Dialog)
        self.pushButtonClose.setGeometry(QtCore.QRect(290, 260, 93, 28))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 361, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_NN_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_NN_2.setText("")
        self.label_NN_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NN_2.setObjectName("label_NN_2")
        self.gridLayout.addWidget(self.label_NN_2, 2, 2, 1, 1)
        self.label_NN_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_NN_3.setText("")
        self.label_NN_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NN_3.setObjectName("label_NN_3")
        self.gridLayout.addWidget(self.label_NN_3, 3, 2, 1, 1)
        self.label_NN_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_NN_1.setText("")
        self.label_NN_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NN_1.setObjectName("label_NN_1")
        self.gridLayout.addWidget(self.label_NN_1, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 3, 1, 1, 1)
        self.pushButtonApply = QtWidgets.QPushButton(Dialog)
        self.pushButtonApply.setGeometry(QtCore.QRect(190, 260, 93, 28))
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 311, 81))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Neural network"))
        self.pushButtonClose.setText(_translate("Dialog", "Close"))
        self.label_2.setText(_translate("Dialog", "Result"))
        self.label_4.setText(_translate("Dialog", "NN #2"))
        self.label_3.setText(_translate("Dialog", "NN #1"))
        self.label_5.setText(_translate("Dialog", "NN #3"))
        self.label.setText(_translate("Dialog", "Channel"))
        self.pushButtonApply.setText(_translate("Dialog", "Apply"))
        self.label_6.setText(_translate("Dialog", "Neural network 1 is trained on scaled channel 2.\n"
"\n"
"Neural network 2 is trained on imf8 channel 1.\n"
"\n"
"Neural network 3 is trained on channel 1 and 2."))
