# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_file_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Open)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 361, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditMeta = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditMeta.setObjectName("lineEditMeta")
        self.gridLayout.addWidget(self.lineEditMeta, 3, 1, 1, 1)
        self.lineEditCH2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditCH2.setObjectName("lineEditCH2")
        self.gridLayout.addWidget(self.lineEditCH2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditCH1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditCH1.setObjectName("lineEditCH1")
        self.gridLayout.addWidget(self.lineEditCH1, 0, 1, 1, 1)
        self.lineEditCompCh = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditCompCh.setObjectName("lineEditCompCh")
        self.gridLayout.addWidget(self.lineEditCompCh, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 191, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Open files"))
        self.label_3.setText(_translate("Dialog", "Comp. Channel"))
        self.lineEditMeta.setText(_translate("Dialog", "D:\\учеба\\МПИ\\data\\signal.txt"))
        self.lineEditCH2.setText(_translate("Dialog", "D:\\учеба\\МПИ\\data\\K.10"))
        self.label.setText(_translate("Dialog", "CH1"))
        self.label_4.setText(_translate("Dialog", "Metadata"))
        self.label_2.setText(_translate("Dialog", "CH2"))
        self.lineEditCH1.setText(_translate("Dialog", "D:\\учеба\\МПИ\\data\\K.9"))
        self.lineEditCompCh.setText(_translate("Dialog", "D:\\учеба\\МПИ\\data\\K.8"))
        self.label_5.setText(_translate("Dialog", "Enter the file paths"))
