# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_trace.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(324, 324)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-40, 270, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 40, 281, 171))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.checkBoxUnload = QtWidgets.QCheckBox(Dialog)
        self.checkBoxUnload.setGeometry(QtCore.QRect(20, 230, 161, 20))
        self.checkBoxUnload.setObjectName("checkBoxUnload")
        self.checkBoxSelAll = QtWidgets.QCheckBox(Dialog)
        self.checkBoxSelAll.setGeometry(QtCore.QRect(20, 10, 81, 20))
        self.checkBoxSelAll.setChecked(True)
        self.checkBoxSelAll.setObjectName("checkBoxSelAll")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Trace filter"))
        self.checkBoxUnload.setText(_translate("Dialog", "Unload nunused traces"))
        self.checkBoxSelAll.setText(_translate("Dialog", "Select all"))
